# Generated by Django 4.0.6 on 2022-07-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='short_url',
            new_name='ShortUrls',
        ),
    ]
